<?php

namespace FormularioBundle\Repository;

/**
 * CompetenciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompetenciaRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCompetencias($em)
    {        
        $query = $em->createQueryBuilder()
        ->select("a.id,"
                ."a.nombre")
        ->from('FormularioBundle:Competencia', 'a');            
//        ->where('a.empresaId = :empresaId')->setParameter('empresaId', $empresaId);

        $rows=$query->getQuery()->getArrayResult();
        
        $choices = array('' => '');
        foreach ($rows as  $row) {
            $choices[$row["nombre"]] = $row["id"];
        }        
        return $choices;       
    }
}
