<?php

namespace FormularioBundle\Repository;

/**
 * PerfilCompetenciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PerfilCompetenciaRepository extends \Doctrine\ORM\EntityRepository
{
}
